# Generated by Django 2.1.1 on 2018-09-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocess', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
