# Generated by Django 2.1.1 on 2018-09-13 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoprocess', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 9, 13, 0, 0))),
                ('info', models.TextField(default='')),
            ],
        ),
    ]
